/* introduce_handoff.c -- generated by Trunnel v1.4.3.
 * https://gitweb.torproject.org/trunnel.git
 * You probably shouldn't edit this file.
 */
#include <stdlib.h>
#include "trunnel-impl.h"

#include "introduce_handoff.h"

#define TRUNNEL_SET_ERROR_CODE(obj) \
  do {                              \
    (obj)->trunnel_error_code_ = 1; \
  } while (0)

#if defined(__COVERITY__) || defined(__clang_analyzer__)
/* If we're runnning a static analysis tool, we don't want it to complain
 * that some of our remaining-bytes checks are dead-code. */
int introducehandoff_deadcode_dummy__ = 0;
#define OR_DEADCODE_DUMMY || introducehandoff_deadcode_dummy__
#else
#define OR_DEADCODE_DUMMY
#endif

#define CHECK_REMAINING(nbytes, label)                           \
  do {                                                           \
    if (remaining < (nbytes) OR_DEADCODE_DUMMY) {                \
      goto label;                                                \
    }                                                            \
  } while (0)

introduction_handoff_v0_t *
introduction_handoff_v0_new(void)
{
  introduction_handoff_v0_t *val = trunnel_calloc(1, sizeof(introduction_handoff_v0_t));
  if (NULL == val)
    return NULL;
  val->blob_magic = INTRODUCTION_MAGIC;
  return val;
}

/** Release all storage held inside 'obj', but do not free 'obj'.
 */
static void
introduction_handoff_v0_clear(introduction_handoff_v0_t *obj)
{
  (void) obj;
  TRUNNEL_DYNARRAY_WIPE(&obj->plaintext);
  TRUNNEL_DYNARRAY_CLEAR(&obj->plaintext);
}

void
introduction_handoff_v0_free(introduction_handoff_v0_t *obj)
{
  if (obj == NULL)
    return;
  introduction_handoff_v0_clear(obj);
  trunnel_memwipe(obj, sizeof(introduction_handoff_v0_t));
  trunnel_free_(obj);
}

uint32_t
introduction_handoff_v0_get_blob_magic(introduction_handoff_v0_t *inp)
{
  return inp->blob_magic;
}
int
introduction_handoff_v0_set_blob_magic(introduction_handoff_v0_t *inp, uint32_t val)
{
  if (! ((val == INTRODUCTION_MAGIC))) {
     TRUNNEL_SET_ERROR_CODE(inp);
     return -1;
  }
  inp->blob_magic = val;
  return 0;
}
uint16_t
introduction_handoff_v0_get_blob_version(introduction_handoff_v0_t *inp)
{
  return inp->blob_version;
}
int
introduction_handoff_v0_set_blob_version(introduction_handoff_v0_t *inp, uint16_t val)
{
  if (! ((val == 0))) {
     TRUNNEL_SET_ERROR_CODE(inp);
     return -1;
  }
  inp->blob_version = val;
  return 0;
}
uint16_t
introduction_handoff_v0_get_plaintext_len(introduction_handoff_v0_t *inp)
{
  return inp->plaintext_len;
}
int
introduction_handoff_v0_set_plaintext_len(introduction_handoff_v0_t *inp, uint16_t val)
{
  inp->plaintext_len = val;
  return 0;
}
size_t
introduction_handoff_v0_getlen_plaintext(const introduction_handoff_v0_t *inp)
{
  return TRUNNEL_DYNARRAY_LEN(&inp->plaintext);
}

uint8_t
introduction_handoff_v0_get_plaintext(introduction_handoff_v0_t *inp, size_t idx)
{
  return TRUNNEL_DYNARRAY_GET(&inp->plaintext, idx);
}

int
introduction_handoff_v0_set_plaintext(introduction_handoff_v0_t *inp, size_t idx, uint8_t elt)
{
  TRUNNEL_DYNARRAY_SET(&inp->plaintext, idx, elt);
  return 0;
}
int
introduction_handoff_v0_add_plaintext(introduction_handoff_v0_t *inp, uint8_t elt)
{
#if SIZE_MAX >= UINT16_MAX
  if (inp->plaintext.n_ == UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  TRUNNEL_DYNARRAY_ADD(uint8_t, &inp->plaintext, elt, {});
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}

uint8_t *
introduction_handoff_v0_getarray_plaintext(introduction_handoff_v0_t *inp)
{
  return inp->plaintext.elts_;
}
int
introduction_handoff_v0_setlen_plaintext(introduction_handoff_v0_t *inp, size_t newlen)
{
  uint8_t *newptr;
#if UINT16_MAX < SIZE_MAX
  if (newlen > UINT16_MAX)
    goto trunnel_alloc_failed;
#endif
  newptr = trunnel_dynarray_setlen(&inp->plaintext.allocated_,
                 &inp->plaintext.n_, inp->plaintext.elts_, newlen,
                 sizeof(inp->plaintext.elts_[0]), (trunnel_free_fn_t) NULL,
                 &inp->trunnel_error_code_);
  if (newptr == NULL)
    goto trunnel_alloc_failed;
  inp->plaintext.elts_ = newptr;
  return 0;
 trunnel_alloc_failed:
  TRUNNEL_SET_ERROR_CODE(inp);
  return -1;
}
const char *
introduction_handoff_v0_check(const introduction_handoff_v0_t *obj)
{
  if (obj == NULL)
    return "Object was NULL";
  if (obj->trunnel_error_code_)
    return "A set function failed on this object";
  if (! (obj->blob_magic == INTRODUCTION_MAGIC))
    return "Integer out of bounds";
  if (! (obj->blob_version == 0))
    return "Integer out of bounds";
  if (TRUNNEL_DYNARRAY_LEN(&obj->plaintext) != obj->plaintext_len)
    return "Length mismatch for plaintext";
  return NULL;
}

ssize_t
introduction_handoff_v0_encoded_len(const introduction_handoff_v0_t *obj)
{
  ssize_t result = 0;

  if (NULL != introduction_handoff_v0_check(obj))
     return -1;


  /* Length of u32 blob_magic IN [INTRODUCTION_MAGIC] */
  result += 4;

  /* Length of u16 blob_version IN [0] */
  result += 2;

  /* Length of u16 plaintext_len */
  result += 2;

  /* Length of u8 plaintext[plaintext_len] */
  result += TRUNNEL_DYNARRAY_LEN(&obj->plaintext);
  return result;
}
int
introduction_handoff_v0_clear_errors(introduction_handoff_v0_t *obj)
{
  int r = obj->trunnel_error_code_;
  obj->trunnel_error_code_ = 0;
  return r;
}
ssize_t
introduction_handoff_v0_encode(uint8_t *output, const size_t avail, const introduction_handoff_v0_t *obj)
{
  ssize_t result = 0;
  size_t written = 0;
  uint8_t *ptr = output;
  const char *msg;
#ifdef TRUNNEL_CHECK_ENCODED_LEN
  const ssize_t encoded_len = introduction_handoff_v0_encoded_len(obj);
#endif

  if (NULL != (msg = introduction_handoff_v0_check(obj)))
    goto check_failed;

#ifdef TRUNNEL_CHECK_ENCODED_LEN
  trunnel_assert(encoded_len >= 0);
#endif

  /* Encode u32 blob_magic IN [INTRODUCTION_MAGIC] */
  trunnel_assert(written <= avail);
  if (avail - written < 4)
    goto truncated;
  trunnel_set_uint32(ptr, trunnel_htonl(obj->blob_magic));
  written += 4; ptr += 4;

  /* Encode u16 blob_version IN [0] */
  trunnel_assert(written <= avail);
  if (avail - written < 2)
    goto truncated;
  trunnel_set_uint16(ptr, trunnel_htons(obj->blob_version));
  written += 2; ptr += 2;

  /* Encode u16 plaintext_len */
  trunnel_assert(written <= avail);
  if (avail - written < 2)
    goto truncated;
  trunnel_set_uint16(ptr, trunnel_htons(obj->plaintext_len));
  written += 2; ptr += 2;

  /* Encode u8 plaintext[plaintext_len] */
  {
    size_t elt_len = TRUNNEL_DYNARRAY_LEN(&obj->plaintext);
    trunnel_assert(obj->plaintext_len == elt_len);
    trunnel_assert(written <= avail);
    if (avail - written < elt_len)
      goto truncated;
    memcpy(ptr, obj->plaintext.elts_, elt_len);
    written += elt_len; ptr += elt_len;
  }


  trunnel_assert(ptr == output + written);
#ifdef TRUNNEL_CHECK_ENCODED_LEN
  {
    trunnel_assert(encoded_len >= 0);
    trunnel_assert((size_t)encoded_len == written);
  }

#endif

  return written;

 truncated:
  result = -2;
  goto fail;
 check_failed:
  (void)msg;
  result = -1;
  goto fail;
 fail:
  trunnel_assert(result < 0);
  return result;
}

/** As introduction_handoff_v0_parse(), but do not allocate the output
 * object.
 */
static ssize_t
introduction_handoff_v0_parse_into(introduction_handoff_v0_t *obj, const uint8_t *input, const size_t len_in)
{
  const uint8_t *ptr = input;
  size_t remaining = len_in;
  ssize_t result = 0;
  (void)result;

  /* Parse u32 blob_magic IN [INTRODUCTION_MAGIC] */
  CHECK_REMAINING(4, truncated);
  obj->blob_magic = trunnel_ntohl(trunnel_get_uint32(ptr));
  remaining -= 4; ptr += 4;
  if (! (obj->blob_magic == INTRODUCTION_MAGIC))
    goto fail;

  /* Parse u16 blob_version IN [0] */
  CHECK_REMAINING(2, truncated);
  obj->blob_version = trunnel_ntohs(trunnel_get_uint16(ptr));
  remaining -= 2; ptr += 2;
  if (! (obj->blob_version == 0))
    goto fail;

  /* Parse u16 plaintext_len */
  CHECK_REMAINING(2, truncated);
  obj->plaintext_len = trunnel_ntohs(trunnel_get_uint16(ptr));
  remaining -= 2; ptr += 2;

  /* Parse u8 plaintext[plaintext_len] */
  CHECK_REMAINING(obj->plaintext_len, truncated);
  TRUNNEL_DYNARRAY_EXPAND(uint8_t, &obj->plaintext, obj->plaintext_len, {});
  obj->plaintext.n_ = obj->plaintext_len;
  memcpy(obj->plaintext.elts_, ptr, obj->plaintext_len);
  ptr += obj->plaintext_len; remaining -= obj->plaintext_len;
  trunnel_assert(ptr + remaining == input + len_in);
  return len_in - remaining;

 truncated:
  return -2;
 trunnel_alloc_failed:
  return -1;
 fail:
  result = -1;
  return result;
}

ssize_t
introduction_handoff_v0_parse(introduction_handoff_v0_t **output, const uint8_t *input, const size_t len_in)
{
  ssize_t result;
  *output = introduction_handoff_v0_new();
  if (NULL == *output)
    return -1;
  result = introduction_handoff_v0_parse_into(*output, input, len_in);
  if (result < 0) {
    introduction_handoff_v0_free(*output);
    *output = NULL;
  }
  return result;
}
